class flMidiEvent:
    handled	: bool
    timestamp	: int
    status	: int
    data1	: int
    data2	: int
    port	: int
    note	: int
    pressure	: int
    progNum	: int
    controlNum	: int
    controlVal	: int
    pitchBend	: int
    sysex	: bytes 
    isIncrement	: bool 
    res	: int
    inEv	: int
    outEv	: int
    midiId	: int
    midiChan	: int
    midiChanEx	: int
    pmeflags : int